### ISSUE TITLE
Fix labby config show for when an ENV var is used

### ISSUE THREAD

**Issue by davidban77** [davidban77/labby#17]
If the configuration file has an environment variable reference like:

```toml
[environment.example.providers.gs-gns3]
    server_url = "https://gns3.example"
    kind = "gns3"
    user = "my-user"
    password = "${GNS3_PASSWORD}"
```
The `${GNS3_PASSWORD}` will try to render or get the value from the environment (or `.env`), but it should render it without the value.
