### ISSUE TITLE
Is it possible to build a network with ubuntu end hosts with static IPs

### ISSUE THREAD

**Issue by srj31** [davidban77/labby#36]
#### Description
I am attempting to create a network topology similar to the screenshot but includes more hosts and routers. The main issue I am currently facing is the bootstrap phase where the error includes a missing config template for ubuntu_desktop net_os and the switch having None for net_os. 

Will including a proper jinja2 config file for other operating systems allow for configuring the interfaces via labby rather than manually configuring individual hosts?

#### Screenshots
The simpler network topology built via labby
<img width="496" alt="Screenshot 2022-12-15 at 11 57 02 PM" src="https://user-images.githubusercontent.com/37596585/207938909-64515257-b50c-4bb4-996f-3a6bba10b484.png">

<br/>
labby get project detail <project_name>
<img width="1230" alt="Screenshot 2022-12-16 at 12 01 51 AM" src="https://user-images.githubusercontent.com/37596585/207939823-80f9fcae-ecd1-42c1-9873-8ccd7041c00f.png">

<br/>

**Comment by davidban77** [comment]
How are you building the topology initially? is it via the `labby build topology` command?

If is like that, there is an option via the `labby_project.yml` file that lets you use external jinja2 templates.

For example:
![Screenshot 2023-01-07 at 12 08 15](https://user-images.githubusercontent.com/16437416/211149946-cd87b95c-572c-455e-8339-fcb2a6281078.png)

The `labby_project.yml` there is a `template` attribute under `main` section in the YAML:
```yaml
---
main:
  name: topology-02
  description: Network Lab for Observability demos
  contributors: ["David Flores <@davidban77>"]
  version: "0.0.7"
  labels: ["telemetry", "observability"]
  template: "./templates/main.j2"
  mgmt_network:
    network: 192.168.2.0/24
    gateway: 192.168.2.1/24
    # Optional to further specify the management IP range
    ip_range: [192.168.2.16, 192.168.2.63]
```
For bootstrap configuration you can specify the `bootstrap.j2` and use conditionals in that file to point to the correct net_os like Ubuntu. This is a bit of that `bootstrap.j2`:
```python
{% if platform == "ios" %}
hostname {{ name }}
! Archiving section
archive
log config
...
{% elif platform == "eos" %}
configure terminal
hostname {{ name }}
...
```

The logic in the `labby build` command should use these templates to render your configuration.

Also, for the devices you DON'T want to have labby to manage it, you can specify `config_managed` to `False`. For example in the `labby_project.yml`
```yaml
nodes_spec:
  - template: "Cisco IOS CSR1kv 17.3.1a"
    nodes: ["lab-r1"]
    net_os: "cisco_ios"
    mgmt_port: "Gi1"
    labels: ["edge", "dub"]

  - template: "Ethernet switch"
    nodes: ["lab-mgmt-switch-01", "lab-mgmt-switch-02"]
    net_os: "builtin"
    config_managed: false
    labels: ["mgmt"]
```
